version: '3.7'

services:
  server:
    build:
      context: ./scheduler-api
      dockerfile: Dockerfile
    image: mydynamicscheduler-server
    container_name: mydynamicscheduler-node-server
    command: /usr/src/app/node index.js
    volumes:
      - ./scheduler-api/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./my-dynamic-scheduler
      dockerfile: Dockerfile
    image: mydynamicscheduler-client
    container_name: mydynamicscheduler-react-client
    command: npm start
    volumes:
      - ./my-dynamic-scheduler/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - scheduler-api
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local